name: My Actions
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  my-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: joshjohanning/approveops@v4.0.0
      - uses: joshjohanning/azdo_commit_message_validator@v4.0.0
      - uses: joshjohanning/bulk-github-repo-sync-action@v2.0.0
      - uses: joshjohanning/enforce-github-pat-expiration@v1.0.1
      - uses: joshjohanning/twistlock-results-json-to-markdown-action@v2.0.0
      - uses: joshjohanning/actions-ref-linter@v0.0.1
      - uses: joshjohanning/bulk-github-repo-settings-sync-action@v2.0.3
      - uses: joshjohanning/organization-readme-badge-generator@v2.0.1
      - uses: joshjohanning/revoke-github-ssh-key-sso-authorization@v1.0.0
      - uses: joshjohanning/ensure-immutable-actions@v2.1.0
      - uses: joshjohanning/nodejs-actions-starter-template@v2.0.1
      - uses: joshjohanning/text-to-emoji-action@v1.0.0
      - uses: joshjohanning/npm-version-check-action@v2.0.0
      - uses: joshjohanning/publish-github-action@v3.0.0
      - uses: joshjohanning/generate-org-repos-sbom-action@v1.0.0

  my-actions-as-shas:
    runs-on: ubuntu-latest
    steps:
      - uses: joshjohanning/nodejs-actions-starter-template@8613b2f57160af312e32754e692f20639fee595f
